name: Deploy Javadoc to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Extract Maven Version
        id: project_version
        working-directory: ./api
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Generate Javadoc
        working-directory: ./api
        run: mvn javadoc:javadoc

      - name: Copy Javadoc via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "api/target/site/apidocs/*"
          target: "/var/www/jozelot.de/jd.jozelot.de/pages/main/jmanhunt-api/${{ steps.project_version.outputs.VERSION }}"
          strip_components: 4
